services:
  langchain:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn server:app --reload --host 0.0.0.0 --port 8000
