AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Bedrock Agent with Tools API built with Langchain and FastAPI on AWS Lambda

Globals:
  Function:
    Timeout: 300

Parameters:
  AWS_DEFAULT_REGION:
    Type: String
    Description: "AWS Default Region"
  AWS_ACCESS_KEY_ID:
    Type: String
    Description: "AWS Access Key ID"
  AWS_SECRET_ACCESS_KEY:
    Type: String
    Description: "AWS Secret Access Key"
  OPENAI_API_KEY:
    Type: String
    Description: "OpenAI API Key"
  PINECONE_API_KEY:
    Type: String
    Description: "Pinecone API Key"

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Events:
        ApiEvents:
          Type: HttpApi
      Environment:
        Variables:
          AWS_DEFAULT_REGION: !Ref AWS_DEFAULT_REGION
          AWS_ACCESS_KEY_ID: !Ref AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: !Ref AWS_SECRET_ACCESS_KEY
          OPENAI_API_KEY: !Ref OPENAI_API_KEY
          PINECONE_API_KEY: !Ref PINECONE_API_KEY
          RUST_BACKTRACE: 1
          PORT: 8538
      Policies:
      - Statement:
        - Sid: BedrockInvokePolicy
          Effect: Allow
          Action:
          - bedrock:InvokeModelWithResponseStream
          Resource: '*'
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: python3.10-v1

Outputs:
  FastAPIURL:
    Description: "API Gateway endpoint URL for Prod stage for FastAPI function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
  FastAPIFunction:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt FastAPIFunction.Arn
  FastAPIIamRole:
    Description: "Implicit IAM Role created for FastAPI function"
    Value: !GetAtt FastAPIFunctionRole.Arn